Repository Beyond-Imagination/express-boilerplate, pull requests merged in 2022-02, with the labels that each got.

#57 check if error codes are duplicated
  jest.config.json
  src/errors/errors.test.ts
Labels: enhancement

#65 use try catch for loading app
  src/app.ts
Labels: enhancement

#59 chore: github actions for ci 구현
  .github/workflows/ci.yml
Labels: enhancement, help wanted

#66 do not throw error when env file not exists
  src/loaders/env.ts
Labels: bug

#69 add codeowners
  .github/CODEOWNERS
Labels: enhancement
